# Lock down dist to ensure that builds run on a distribution that supports oraclejdk8
dist: trusty
language: ruby
jdk:
  - oraclejdk8
rvm:
  - 2.3.1
install:
  - sudo apt-get install -y freetds-bin freetds-common freetds-dev libct4 libsybdb5
  - rvm use 2.3.1
  - gem install bundler
  - bundle install
script: buildr clean package
git:
  depth: 10
