language: ruby
jdk:
  - oraclejdk8
sudo: false
rvm:
  - 2.1.3
addons:
  apt:
    packages:
    - freetds-dev
install:
  - rvm use 2.1.3
  - gem install bundler
  - bundle install
script: buildr clean package
git:
  depth: 10
