<% prefix = Dbtc.db_prefix(ENV['USER'],ENV['JOB_NAME']) %>
devhost: &devhost
  username: <%= Dbtc.env('DB_SERVER_USERNAME') %>
  password: <%= Dbtc.env('DB_SERVER_PASSWORD') %>
  host: <%= Dbtc.env('DB_SERVER_HOST') %>
<% if Dbtc.sql_server? %>
  port: <%= Dbtc.env('DB_SERVER_PORT','1433') %>
  instance: <%= Dbtc.env('DB_SERVER_INSTANCE','') %>
  force_drop: true
<% unless defined?(JRUBY_VERSION) %>
  timeout: 10000
<% end %>
<% else %>
  port: <%= Dbtc.env('DB_SERVER_PORT','5432') %>
<% end %>

#
# Test configurations
#

test: &test
  database: <%= prefix %>TIMERS_TEST
  <<: *devhost
